server:
  port: 8081

#---
spring:
#  profiles: jms-template, jms-listener
  # The values given here are actually the default values. But they are explicitly
  # set here as an example of setting the Artemis properties.
  jms:
    template:
      receive-timeout: 2

  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest
    template:
      receive-timeout: 30000
#    broker-url: http://localhost:8161

#---
#spring:
#  profiles: kafka-listener
#
#  kafka:
#    bootstrap-servers:
#      - localhost:9092
#    template:
#      default-topic: tacocloud.orders.topic
#    consumer:
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      group-id: tacocloud_kitchen
#      properties:
#        spring.json.trusted.packages: tacos